language: node_js
sudo: false
node_js:
- '8'
dist: trusty
sudo: false
addons:
  chrome: stable
script:
- yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: npmjs@heise.de
  api_key:
    secure: "QAYvXR/BWoHuKcRa0DZQPWsjXuKzZGDlZXAVYuySce9Wh7sz4mpUQHhZGrSYijognBmkXQIHDcyQ88SM3qPsHv56VjzMWBNGNss1ZUQwsJPRDQ2woXBf95SH6MWeCdvt5oBVSJBpWnNVsoHENWPZWuqiNT+xVAq7oW56DTmNJt49WihCmYq+qDFnKtWCXNlFCfVf0ogLdxnPOH36YjINlXPwxn5JrsAWEp/wznMNe9NpWrodMWIzsA5NiMXJCirKZMPxeTYouH+8txckv8S8iIWykaMWbb90Me23CDN1nU9ZkMlvedggerSbebyz3epgw1zZVxRSPc9GyHUGRyPXSoR04OFmPvmjJGb5sOiqoRhf9l2g9q8PlTybLyfxrJvAWnXuET7BiAghrjqcjNTEkP+ErjY2N4YDL19ACHpKjGC6WArD/+rWCkNTiw43E8gEdzH63ruEzwWMKRyyLaQpGjE7c/HHFjRD+r22YMZaJ5MsOZFFP/NCORCAIlhdmsTdPuMgr2P66gFImFPIaAIhl1EXXAJ1wPn8UxpxTTB3BxtdagMk6mFggX+aY0MRk4BXerVs41SB8NUz2UR95sicreYds9ZR5HRMnfgVz4gotN67UrwlkPExt8ox++3sbddR0IPI4x3CdX4gQQHYPAhMLqdcE8+GbFSSQttfaqbt9uc="
  on:
    tags: true
    repo: heiseonline/embetty
    node_js: '8'
