language: node_js
sudo: false
node_js:
- '8'
script:
- yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: npmjs@heise.de
  api_key:
    secure: "qxC5o2Bc0cOTxqjDyCMIkY+9+4pfZobATq2MNP/4wxy4cqNNsuBjhy335bE44n/z08XIlODJYuJHZfq8wb1NpHC+JmD5iZM/QaYkwi5XFm73R0iZ2gAivQGVnv2Fvu4D8SdtpseFP3YBoX/c8eRbHnImkIGUrObPXvqhc9b0+vyzgdZSrRy7a/wkUbDLqi+Z8iI/mTAFr/Ur3yTmD9hlw8NFw3HHCCqzwVj7Fdb9vv9bLT+1SxHj96tcHWRdUDjV48tfKyID6DCpoGreJos1L0P5LGhJgVsjgQyaI3JEzxChHJA0IVexW6bLNctZvT9yTgaW1AGKr4f8NPED0Vthv59vWjf0ptEVPSt4NFV9XCHpWrPiW+koTxJPNADkDQ/YGJpHKG5nT85psHQbWZT2AmKuvGue7MCyYrZdaKttWWFTc+dZi+sDFg64iiw4hyU0L+9xG+0bxSBo2kVFG2cn7ie3LYRKtZv5JwybqICHehDscF5Ha1lw++7ie65VD/3VlIlBd9EYcp3pbYwqeHLClXDDYieSVOcA/41V1vZNFNfl8uuDGLJLXi38qslq+xA7OyfXjtTCaSC+BFc4lFLCn2P/fGFzBpnxgoTI27LDI/puu80rjVs20nn2fyitHN3ebbpe9cvwC7uGNKS5NwQGUIS+WdRhNRn1S7OOe4IH8bs="
  on:
    tags: true
    repo: heiseonline/embetty-server
    node_js: '8'
env:
  global:
    secure: ZJ2A+YqqLfcRmOYG6+36ZapATBi2sVRjvHr+o6rVHfFIz6ltQCam2HvPmaHjIEu5A/ha1kktMtFFzWXiz2MjaGGe2754Xcv91832Uq9F5bxnHimDM6EeCS6EMvWyqwuaRKTSFoSJA4S8QvCWkTEVr/LkUTdxwDAKa/VXtxi4/E2D9cz28tKMEUFh4EVRewB8XOmg38VjGuoy9QtuHF/iXAif4TsPu9wXCRvLtdW00dyRAsKj2myHPbuvZTW1w5hBi4u7B3TcwxmORxBrDHmppU8IioVpIHhHnR81RdSJkqjq6ehch3B4HpMeFt0XyJTedHjtFMN7Kn+n1y8tLcscbdazsS8GgzFpq6tWWfkGhI9hJ0hucwaXXm8HZudlaBIQaizEMScwYiq8kHq7P1dyKl24WFpTf9kJivU+j110s+oxpiRXRVaDcbyJ51c+RnqSzc3KMDtJX8zk/bN+J83wXdkOIBsHgehKQgb7PhMGAiiVtaxZt/h9bp0iMScXwd/MUlGA5XUizU46EE3BkU9meD110RJFUAHfCc64YIfTJmCoa6wpOIRQ0ZoTsWlWAMayHL/k0ZFQXDRY/rGuwk8NNFndniq+J0fsVhGVQhOYk4UXxwskutSJf2LUYa3lOVF/NHni7msYbuQFFYV06pB2NekrZu3Xj2Zsjc6JEX+bLec=
